In [1]:

import sys
if 'google.colab' in sys.modules:
    !pip install utdquake

lib = None
lib = "/home/emmanuel/ecastillo/dev/utdquake"
if lib is not None:
    sys.path.append(lib)

Collecting utdquake
  Downloading utdquake-0.0.12-py3-none-any.whl.metadata (4.2 kB)
Collecting certifi==2024.12.14 (from utdquake)
  Downloading certifi-2024.12.14-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: charset-normalizer==3.4.1 in /usr/local/lib/python3.11/dist-packages (from utdquake) (3.4.1)
Requirement already satisfied: contourpy==1.3.1 in /usr/local/lib/python3.11/dist-packages (from utdquake) (1.3.1)
Requirement already satisfied: cycler==0.12.1 in /usr/local/lib/python3.11/dist-packages (from utdquake) (0.12.1)
Collecting decorator==5.1.1 (from utdquake)
  Downloading decorator-5.1.1-py3-none-any.whl.metadata (4.0 kB)
Collecting fonttools==4.55.3 (from utdquake)
  Downloading fonttools-4.55.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (165 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 165.1/165.1 kB 2.8 MB/s eta 0:00:00
Requirement already satisfied: greenlet==3.1.1 in /usr/local/lib/python3.11/dist-packages (from utdquake) (3.1.1)
Requirement already satisfied: idna==3.10 in /usr/local/lib/python3.11/dist-packages (from utdquake) (3.10)
Requirement already satisfied: kiwisolver==1.4.8 in /usr/local/lib/python3.11/dist-packages (from utdquake) (1.4.8)
Collecting lxml==5.3.0 (from utdquake)
  Downloading lxml-5.3.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: matplotlib==3.10.0 in /usr/local/lib/python3.11/dist-packages (from utdquake) (3.10.0)
Collecting numpy==2.2.1 (from utdquake)
  Downloading numpy-2.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 1.4 MB/s eta 0:00:00
Collecting obspy==1.4.1 (from utdquake)
  Downloading obspy-1.4.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.7 kB)
Requirement already satisfied: packaging==24.2 in /usr/local/lib/python3.11/dist-packages (from utdquake) (24.2)
Collecting pandas==2.2.3 (from utdquake)
  Downloading pandas-2.2.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 3.7 MB/s eta 0:00:00
Requirement already satisfied: pillow==11.1.0 in /usr/local/lib/python3.11/dist-packages (from utdquake) (11.1.0)
Requirement already satisfied: pyparsing==3.2.1 in /usr/local/lib/python3.11/dist-packages (from utdquake) (3.2.1)
Collecting pyproj==3.7.0 (from utdquake)
  Downloading pyproj-3.7.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (31 kB)
Collecting python-dateutil==2.9.0.post0 (from utdquake)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz==2024.2 (from utdquake)
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: requests==2.32.3 in /usr/local/lib/python3.11/dist-packages (from utdquake) (2.32.3)
Collecting scipy==1.15.1 (from utdquake)
  Downloading scipy-1.15.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 2.4 MB/s eta 0:00:00
Requirement already satisfied: six==1.17.0 in /usr/local/lib/python3.11/dist-packages (from utdquake) (1.17.0)
Collecting SQLAlchemy==1.4.54 (from utdquake)
  Downloading SQLAlchemy-1.4.54-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Requirement already satisfied: tqdm==4.67.1 in /usr/local/lib/python3.11/dist-packages (from utdquake) (4.67.1)
Collecting tzdata==2024.2 (from utdquake)
  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3==2.3.0 in /usr/local/lib/python3.11/dist-packages (from utdquake) (2.3.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from obspy==1.4.1->utdquake) (75.1.0)
Downloading utdquake-0.0.12-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.1/64.1 kB 2.7 MB/s eta 0:00:00
Downloading certifi-2024.12.14-py3-none-any.whl (164 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.9/164.9 kB 10.8 MB/s eta 0:00:00
Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Downloading fonttools-4.55.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 45.0 MB/s eta 0:00:00
Downloading lxml-5.3.0-cp311-cp311-manylinux_2_28_x86_64.whl (5.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 65.4 MB/s eta 0:00:00
Downloading numpy-2.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 54.1 MB/s eta 0:00:00
Downloading obspy-1.4.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.5/14.5 MB 54.4 MB/s eta 0:00:00
Downloading pandas-2.2.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 60.7 MB/s eta 0:00:00
Downloading pyproj-3.7.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 64.7 MB/s eta 0:00:00
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 14.7 MB/s eta 0:00:00
Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.0/508.0 kB 30.8 MB/s eta 0:00:00
Downloading scipy-1.15.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (40.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 MB 10.0 MB/s eta 0:00:00
Downloading SQLAlchemy-1.4.54-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 55.5 MB/s eta 0:00:00
Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.6/346.6 kB 23.2 MB/s eta 0:00:00
Installing collected packages: pytz, tzdata, SQLAlchemy, python-dateutil, numpy, lxml, fonttools, decorator, certifi, scipy, pyproj, pandas, obspy, utdquake
  Attempting uninstall: pytz
    Found existing installation: pytz 2025.1
    Uninstalling pytz-2025.1:
      Successfully uninstalled pytz-2025.1
  Attempting uninstall: tzdata
    Found existing installation: tzdata 2025.1
    Uninstalling tzdata-2025.1:
      Successfully uninstalled tzdata-2025.1
  Attempting uninstall: SQLAlchemy
    Found existing installation: SQLAlchemy 2.0.38
    Uninstalling SQLAlchemy-2.0.38:
      Successfully uninstalled SQLAlchemy-2.0.38
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.8.2
    Uninstalling python-dateutil-2.8.2:
      Successfully uninstalled python-dateutil-2.8.2
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  Attempting uninstall: lxml
    Found existing installation: lxml 5.3.1
    Uninstalling lxml-5.3.1:
      Successfully uninstalled lxml-5.3.1
  Attempting uninstall: fonttools
    Found existing installation: fonttools 4.56.0
    Uninstalling fonttools-4.56.0:
      Successfully uninstalled fonttools-4.56.0
  Attempting uninstall: decorator
    Found existing installation: decorator 4.4.2
    Uninstalling decorator-4.4.2:
      Successfully uninstalled decorator-4.4.2
  Attempting uninstall: certifi
    Found existing installation: certifi 2025.1.31
    Uninstalling certifi-2025.1.31:
      Successfully uninstalled certifi-2025.1.31
  Attempting uninstall: scipy
    Found existing installation: scipy 1.13.1
    Uninstalling scipy-1.13.1:
      Successfully uninstalled scipy-1.13.1
  Attempting uninstall: pyproj
    Found existing installation: pyproj 3.7.1
    Uninstalling pyproj-3.7.1:
      Successfully uninstalled pyproj-3.7.1
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.2.3 which is incompatible.
pytensor 2.27.1 requires numpy<2,>=1.17.0, but you have numpy 2.2.1 which is incompatible.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 2.2.1 which is incompatible.
numba 0.61.0 requires numpy<2.2,>=1.24, but you have numpy 2.2.1 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.2.1 which is incompatible.
gensim 4.3.3 requires scipy<1.14.0,>=1.7.0, but you have scipy 1.15.1 which is incompatible.
moviepy 1.0.3 requires decorator<5.0,>=4.0.2, but you have decorator 5.1.1 which is incompatible.
thinc 8.2.5 requires numpy<2.0.0,>=1.19.0; python_version >= "3.9", but you have numpy 2.2.1 which is incompatible.
langchain 0.3.19 requires numpy<2,>=1.26.4; python_version < "3.12", but you have numpy 2.2.1 which is incompatible.
ipython-sql 0.5.0 requires sqlalchemy>=2.0, but you have sqlalchemy 1.4.54 which is incompatible.
Successfully installed SQLAlchemy-1.4.54 certifi-2024.12.14 decorator-5.1.1 fonttools-4.55.3 lxml-5.3.0 numpy-2.2.1 obspy-1.4.1 pandas-2.2.3 pyproj-3.7.0 python-dateutil-2.9.0.post0 pytz-2024.2 scipy-1.15.1 tzdata-2024.2 utdquake-0.0.12

# Version (Required)

In [1]:
import utdquake
from packaging.version import Version

current_version = Version(utdquake.__version__)
required_version = Version("0.0.12")

if current_version < required_version:
    raise Exception(f"Please update utdquake to at least version {required_version}")

# UTDClient

## get custom stations

In [2]:
from utdquake.clients.fdsn.client import Client

provider = "IRIS"
out = "./custom_events"

client =  Client(provider)
sta = client.get_custom_stations(output_folder=out,network="TX",station="PB*")
print(sta.head(10))

     sta_id network station   latitude   longitude  elevation  \
0   TX.PB01      TX    PB01  30.943670 -103.781120     1010.0
1   TX.PB02      TX    PB02  31.408951 -103.510162      792.0
3   TX.PB03      TX    PB03  31.083840 -103.513950      871.0
4   TX.PB04      TX    PB04  31.186970 -103.269400      812.0
5   TX.PB05      TX    PB05  30.919780 -103.324700      957.0
6   TX.PB06      TX    PB06  31.647200 -103.218250      831.0
9   TX.PB07      TX    PB07  31.579350 -103.667930      856.0
10  TX.PB08      TX    PB08  30.891740 -102.907360      926.0
11  TX.PB09      TX    PB09  31.774145 -104.301444     1139.0
12  TX.PB10      TX    PB10  31.283607 -103.754585      858.0

             starttime endtime                       site_name
0  2017-09-13 00:00:00     NaT            Balmorhea State Park
1  2017-01-27 00:00:00     NaT  Crockett Middle School (Pecos)
3  2021-07-28 03:30:00     NaT                        Verhalen
4  2019-02-12 00:00:00     NaT                        Verhalen
5  2016-11-05 00:00:00     NaT                 Permian Basin 5
6  2017-10-11 00:00:00     NaT                           Pyote
9  2022-12-12 20:00:01     NaT                         Mentone
10 2017-05-25 00:00:00     NaT                   Fort Stockton
11 2019-05-22 00:00:00     NaT                Culberson County
12 2018-10-17 00:00:00     NaT              Southeast of Toyah

## get custom events

In [3]:
from obspy import UTCDateTime
from utdquake.clients.fdsn.client import Client

region = [-104.84329,-103.79942,31.39610,31.91505]
provider = "USGS"
out = "./custom_events"

client =  Client(provider)
cat,picks,mag = client.get_custom_events(starttime=UTCDateTime("2024-04-18T23:00:00"),
                        endtime=UTCDateTime("2024-04-19T23:00:00"),
                        minlatitude=region[2], maxlatitude=region[3],
                        minlongitude=region[0], maxlongitude=region[1],
                        debug=True,
                        output_folder=out,
                        )

Event id 1/7: tx2024hrey
Event id 2/7: tx2024hrgy
Event id 3/7: tx2024hriz
Event id 4/7: tx2024hrlf
Event id 5/7: tx2024hrwl
Event id 6/7: tx2024hrwo
Event id 7/7: tx2024hstr

# How to read?

FIles in your ouput folder

In [4]:
import os
print(os.listdir(out))

['mags.db', 'stations.csv', 'picks.db', 'origin.csv']

picks and mags are in database format

In [6]:
import os

stations_path = os.path.join(out,"stations.csv")
events_path = os.path.join(out,"origin.csv")
picks_path = os.path.join(out,"picks.db")
mags_path = os.path.join(out,"mags.db")

read catalog

In [15]:
from utdquake.core.event.catalog import read_catalog
help(read_catalog)

Help on function read_catalog in module utdquake.core.event.catalog:

read_catalog(events_path, xy_epsg, stations_path=None, author='UTDQuake') -> dict
    Load earthquake data from CSV files and return a Catalog object.

    Parameters:
    ----------
    events_path : str
        Path to the CSV file containing event data.
    xy_epsg : int
        EPSG code for coordinate transformation.
    stations_path : str, optional
        Path to the CSV file containing station data. Default is None.
    author : str, default="UTDQuake"
        Author/source of the data.

    Returns:
    -------
    Catalog
        A Catalog object containing the loaded event and station data.

    Notes:
    ------
    - The `Events` and `Stations` classes must be defined elsewhere in your code
      to properly handle the loaded data.
    - If `stations_path` is not provided, the station data will not be loaded.

In [8]:
catalog = read_catalog(events_path=events_path,
                       xy_epsg="EPSG:3116",
                       stations_path=stations_path)
print(catalog)

Catalog | 7 events, stations: True

events

In [11]:
events = catalog.events
print(events)

Events | 7 events

You can execute multiple functions in your Events class. Review the following documentation

In [16]:
from utdquake.core.event.events import Events
help(Events)

Help on class Events in module utdquake.core.event.events:

class Events(utdquake.core.event.spatial.Points)
 |  Events(*args, **kwargs) -> None
 |
 |  A class representing a collection of seismic events.
 |
 |  Method resolution order:
 |      Events
 |      utdquake.core.event.spatial.Points
 |      utdquake.core.event.data.DataFrameHelper
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, *args, **kwargs) -> None
 |      Initialize the Events class with mandatory and optional attributes.
 |
 |      Parameters:
 |      - *args: Positional arguments passed to the parent class.
 |      - **kwargs: Keyword arguments passed to the parent class.
 |
 |  __str__(self, extended=False) -> str
 |      Return a string representation of the Events instance.
 |
 |      Parameters:
 |      - extended (bool, optional): If True, include detailed information. Defaults to False.
 |
 |      Returns:
 |      - str: Formatted string summarizing the event data.
 |
 |  get_picks(self, picks_path, stations=None, author='UTDQuake', debug=False)
 |      Load and return picks data associated with events.
 |
 |      Parameters:
 |      ----------
 |      picks_path : str
 |          Path to the picks data file.
 |      stations : Stations, optional
 |          An instance of the Stations class containing station information.
 |          If provided, the function merges station data with pick data.
 |      author : str, default="UTDQuake"
 |          Author/source of the picks data.
 |
 |      Returns:
 |      -------
 |      Picks
 |          An instance of the Picks class containing the loaded picks data.
 |
 |  query(self, starttime=None, endtime=None, ev_ids=None, agencies=None, mag_lims=None, region_lims=None, general_region=None, region_from_src=None)
 |      Query and filter events based on various criteria.
 |
 |      Parameters:
 |      - starttime (datetime, optional): Start time for filtering events.
 |      - endtime (datetime, optional): End time for filtering events.
 |      - ev_ids (list, optional): List of event IDs to include.
 |      - agencies (list, optional): List of agencies to include.
 |      - mag_lims (tuple, optional): Magnitude range as (min, max).
 |      - region_lims (list, optional): Rectangular region limits [lon_min, lon_max, lat_min, lat_max].
 |      - general_region (list of tuples, optional): Polygon defining a general region [(lon, lat), ...].
 |      - region_from_src (tuple, optional): Source-based region definition (latitude, longitude, max_radius, max_azimuth).
 |
 |      Returns:
 |      - Events: The filtered Events object.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from utdquake.core.event.spatial.Points:
 |
 |  filter_by_r_az(self, latitude, longitude, r, az=None)
 |      Filter data points based on distance (r) and optionally azimuth (az).
 |
 |      Parameters:
 |      ----------
 |      latitude : float
 |          Latitude of the reference point.
 |      longitude : float
 |          Longitude of the reference point.
 |      r : float
 |          Maximum distance in kilometers to filter data points.
 |      az : float, optional
 |          Maximum azimuth in degrees to filter data points (default is None).
 |
 |      Returns:
 |      -------
 |      self : object
 |          The object with updated data after filtering.
 |
 |  filter_general_region(self, polygon)
 |      Filter points inside a specified polygon.
 |
 |      Parameters:
 |      - polygon (list of tuples): List of (lon, lat) defining the polygon boundary.
 |
 |  filter_rectangular_region(self, region_lims)
 |      Filter points within a rectangular region.
 |
 |      Parameters:
 |      - region_lims (list): [lon_min, lon_max, lat_min, lat_max].
 |
 |  get_minmax_coords(self, padding=None)
 |      Return the bounding coordinates with optional padding.
 |
 |  get_region(self, padding=None)
 |      Get the bounding region based on coordinate limits.
 |
 |      Parameters:
 |      - padding (list or float, optional):
 |          - If list: Padding for each side [west, east, south, north] in degrees.
 |          - If float/int: Percentage-based padding (0 to 1) of the region size.
 |
 |  sort_data_by_source(self, source: utdquake.core.event.spatial.SinglePoint, ascending: bool = False)
 |      Sorts data by distance from a specified source location.
 |
 |      Parameters:
 |      - source (SinglePoint): Reference location.
 |      - ascending (bool, optional): Whether to sort in ascending order. Defaults to False.
 |
 |      Returns:
 |      - pd.DataFrame: Data sorted by distance from the source.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from utdquake.core.event.data.DataFrameHelper:
 |
 |  __getitem__(self, key)
 |
 |  __len__(self)
 |      Return the number of rows in the DataFrame.
 |
 |  __setitem__(self, key, value)
 |
 |  append(self, data)
 |      Append new data to the DataFrameHelper.
 |
 |      Parameters:
 |          data (pd.DataFrame): DataFrame to append.
 |
 |      Returns:
 |          DataFrameHelper: Updated DataFrameHelper instance.
 |
 |      Raises:
 |          TypeError: If the input data is not a DataFrame.
 |
 |  copy(self)
 |      Create a deep copy of the DataFrameHelper instance.
 |
 |      Returns:
 |      --------
 |      DataFrameHelper
 |          A deep copy of the current instance.
 |
 |  filter(self, key, start=None, end=None)
 |      Filter data in the catalog based on a range of values for a specified column.
 |
 |      Parameters:
 |      -----------
 |      key : str
 |          Name of the column to filter.
 |      start : int, float, or datetime.datetime, optional
 |          The minimum value for the filter range. Must match the data type of `data[key]`.
 |      end : int, float, or datetime.datetime, optional
 |          The maximum value for the filter range. Must match the data type of `data[key]`.
 |
 |      Returns:
 |      --------
 |      self : DataFrameHelper
 |          The updated DataFrameHelper instance with filtered rows.
 |
 |  remove_data(self, rowval)
 |      Remove rows from the data based on specified conditions.
 |
 |      Parameters:
 |          rowval (dict): Dictionary where keys are column names and values are lists of values to remove.
 |
 |      Returns:
 |          DataFrameHelper: Updated DataFrameHelper instance.
 |
 |      Raises:
 |          Exception: If `rowval` is not a dictionary.
 |
 |  select_data(self, rowval)
 |      Select rows in the data based on specified criteria.
 |
 |      Parameters:
 |      -----------
 |      rowval : dict
 |          A dictionary specifying the columns and the values to select.
 |          Keys represent column names, and values are lists of values to filter by.
 |
 |      Returns:
 |      --------
 |      self : DataFrameHelper
 |          The updated DataFrameHelper with only the selected rows.
 |
 |  sort_values(self, **args)
 |      Sort the DataFrame by the specified columns.
 |
 |      Parameters:
 |      -----------
 |      args : dict
 |          Arguments passed to `pd.DataFrame.sort_values`.
 |
 |      Returns:
 |      --------
 |      self : DataFrameHelper
 |          The updated DataFrameHelper instance with sorted data.
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties inherited from utdquake.core.event.data.DataFrameHelper:
 |
 |  empty
 |      Check if the DataFrame is empty.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from utdquake.core.event.data.DataFrameHelper:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object

You can export your results in a dataframe if you need it

In [14]:
data = events.data
data

,ev_id,ev_type,agency,origin_time,longitude,latitude,depth,loc_method_id,earth_model_id,magnitude,...,qc_used_phase_count,qc_associated_station_count,qc_used_station_count,qc_arrivals_rms,qc_azimuthal_gap,qc_minimum_station_distance,qc_maximum_station_distance,qc_median_station_distance,x[km],y[km]
0,tx2024hrey,earthquake,TX,2024-04-19 00:33:29.083274,-103.884,31.488,6074.2,NonLinLoc,PB1D-20170918-topoLV,1.8,...,23,NaN,20,0.1,60.0,0.1,0.2,0.2,4392.772121,-1888.577341
1,tx2024hrgy,earthquake,TX,2024-04-19 01:33:51.844213,-104.194,31.612,4920.7,NonLinLoc,PB1D-20170918-topoLV,1.8,...,40,NaN,29,0.1,67.0,0.1,0.3,0.2,4416.730671,-1915.336785
2,tx2024hriz,earthquake,TX,2024-04-19 02:34:59.666935,-103.937,31.605,5920.4,NonLinLoc,PB1D-20170918-topoLV,1.6,...,17,NaN,12,0.1,84.0,0.1,0.1,0.1,4408.095791,-1889.779315
3,tx2024hrlf,earthquake,TX,2024-04-19 03:43:00.012014,-104.287,31.717,6151.1,NonLinLoc,PB1D-20170918-topoLV,2.6,...,21,NaN,15,0.2,60.0,0.0,0.2,0.2,4431.905519,-1920.908784
4,tx2024hrwl,earthquake,TX,2024-04-19 09:23:13.067845,-104.410,31.677,5638.4,NonLinLoc,PB1D-20170918-topoLV,2.9,...,30,NaN,23,0.1,69.0,0.0,0.3,0.3,4431.000076,-1934.695851
5,tx2024hrwo,earthquake,TX,2024-04-19 09:27:37.173812,-104.417,31.672,6945.8,NonLinLoc,PB1D-20170918-topoLV,2.1,...,24,NaN,20,0.2,66.0,0.0,1.0,0.3,4430.629180,-1935.579455
6,tx2024hstr,earthquake,TX,2024-04-19 21:08:30.469108,-104.198,31.672,7227.8,NonLinLoc,PB1D-20170918-topoLV,2.1,...,61,NaN,35,0.2,62.0,0.1,0.4,0.2,4423.894828,-1913.593013

One of the important functions are get_picks

In [17]:
picks = catalog.get_picks(picks_path=picks_path,author="manual")
print(picks)

Picks | 354 picks, (7 events-60 stations)

/usr/local/lib/python3.11/dist-packages/utdquake/core/event/events.py:158: UserWarning: Some stations do not have coordinates. Activate debug mode in Events.get_picks to display them.
  warnings.warn("Some stations do not have coordinates. Activate debug mode in Events.get_picks to display them.")

In [20]:
from utdquake.core.event.picks import Picks
help(Picks)

Help on class Picks in module utdquake.core.event.picks:

class Picks(utdquake.core.event.data.DataFrameHelper)
 |  Picks(data, author) -> None
 |
 |  A class to manage and process earthquake picks data.
 |
 |  Attributes:
 |  -----------
 |  data : pd.DataFrame
 |      The main DataFrame containing pick information.
 |      Required columns: 'ev_id', 'network', 'station', 'time', 'phase_hint'.
 |  author : str, optional
 |      The author or source of the picks data.
 |
 |  Method resolution order:
 |      Picks
 |      utdquake.core.event.data.DataFrameHelper
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, data, author) -> None
 |      Initialize the Picks class with mandatory columns.
 |
 |      Parameters:
 |      -----------
 |      data : pd.DataFrame
 |          A DataFrame containing picks data.
 |          Required columns: 'ev_id', 'network', 'station', 'time', 'phase_hint'.
 |      author : str, optional
 |          The author or source of the picks data.
 |
 |  __str__(self) -> str
 |      String representation of the Picks class.
 |
 |      Returns:
 |      --------
 |      str
 |          A summary of the number of events and picks in the data.
 |
 |  drop_picks_with_single_phase(self)
 |      Drop picks that have only one phase (e.g., only P or only S) for each event-station pair.
 |
 |      Returns:
 |      --------
 |      Picks
 |          The updated Picks instance with only picks having both P and S phases.
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties defined here:
 |
 |  events
 |      Retrieve the unique event IDs present in the data.
 |
 |      Returns:
 |      --------
 |      list
 |          A list of unique event IDs.
 |
 |  lead_pick
 |      Get the pick with the earliest arrival time.
 |
 |      Returns:
 |      --------
 |      pd.Series
 |          The row corresponding to the earliest pick.
 |
 |  stations
 |      Retrieve unique station IDs from the data.
 |
 |      Returns:
 |      --------
 |      list
 |          A list of unique station IDs in the format 'network.station'.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from utdquake.core.event.data.DataFrameHelper:
 |
 |  __getitem__(self, key)
 |
 |  __len__(self)
 |      Return the number of rows in the DataFrame.
 |
 |  __setitem__(self, key, value)
 |
 |  append(self, data)
 |      Append new data to the DataFrameHelper.
 |
 |      Parameters:
 |          data (pd.DataFrame): DataFrame to append.
 |
 |      Returns:
 |          DataFrameHelper: Updated DataFrameHelper instance.
 |
 |      Raises:
 |          TypeError: If the input data is not a DataFrame.
 |
 |  copy(self)
 |      Create a deep copy of the DataFrameHelper instance.
 |
 |      Returns:
 |      --------
 |      DataFrameHelper
 |          A deep copy of the current instance.
 |
 |  filter(self, key, start=None, end=None)
 |      Filter data in the catalog based on a range of values for a specified column.
 |
 |      Parameters:
 |      -----------
 |      key : str
 |          Name of the column to filter.
 |      start : int, float, or datetime.datetime, optional
 |          The minimum value for the filter range. Must match the data type of `data[key]`.
 |      end : int, float, or datetime.datetime, optional
 |          The maximum value for the filter range. Must match the data type of `data[key]`.
 |
 |      Returns:
 |      --------
 |      self : DataFrameHelper
 |          The updated DataFrameHelper instance with filtered rows.
 |
 |  remove_data(self, rowval)
 |      Remove rows from the data based on specified conditions.
 |
 |      Parameters:
 |          rowval (dict): Dictionary where keys are column names and values are lists of values to remove.
 |
 |      Returns:
 |          DataFrameHelper: Updated DataFrameHelper instance.
 |
 |      Raises:
 |          Exception: If `rowval` is not a dictionary.
 |
 |  select_data(self, rowval)
 |      Select rows in the data based on specified criteria.
 |
 |      Parameters:
 |      -----------
 |      rowval : dict
 |          A dictionary specifying the columns and the values to select.
 |          Keys represent column names, and values are lists of values to filter by.
 |
 |      Returns:
 |      --------
 |      self : DataFrameHelper
 |          The updated DataFrameHelper with only the selected rows.
 |
 |  sort_values(self, **args)
 |      Sort the DataFrame by the specified columns.
 |
 |      Parameters:
 |      -----------
 |      args : dict
 |          Arguments passed to `pd.DataFrame.sort_values`.
 |
 |      Returns:
 |      --------
 |      self : DataFrameHelper
 |          The updated DataFrameHelper instance with sorted data.
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties inherited from utdquake.core.event.data.DataFrameHelper:
 |
 |  empty
 |      Check if the DataFrame is empty.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from utdquake.core.event.data.DataFrameHelper:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object

in dataframe

In [21]:
picks_data = picks.data
picks_data

,ev_id,network,station,location,channel,phase_hint,time,time_lower_error,time_upper_error,author,...,distance,takeoff_angle,time_residual,time_weight,used,utdq_real,utdq_distance,utdq_azimuth,utdq_bazimuth,utdq_time
0,tx2024hrey,TX,PB13,01,HHN,P,2024-04-19 00:33:30.972988,0.3,0.3,Anestis,...,0.073466,121.4,-0.329797,0.805510,1,True,8.187932,26.293424,206.313396,1.889714
1,tx2024hrey,4O,WB04,00,HHZ,P,2024-04-19 00:33:31.222610,0.3,0.3,Anestis,...,0.070619,122.8,-0.034325,1.040132,1,True,NaN,NaN,NaN,2.139336
2,tx2024hrey,TX,PECS,00,HH2,P,2024-04-19 00:33:32.130765,0.2,0.2,Anestis,...,0.118924,106.1,0.020992,1.212390,1,True,NaN,NaN,NaN,3.047491
3,tx2024hrey,4O,WB03,00,HHN,P,2024-04-19 00:33:32.751721,0.2,0.2,Anestis,...,0.142258,100.0,0.184438,0.000000,1,True,NaN,NaN,NaN,3.668447
4,tx2024hrey,TX,PB33,00,HH1,P,2024-04-19 00:33:32.820194,0.3,0.3,Anestis,...,0.152476,96.4,0.057580,1.014601,1,True,16.970122,287.900179,107.811302,3.736920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,tx2024hstr,TX,PB56,00,CHN,S,2024-04-19 21:08:41.489250,0.2,0.2,Fernando,...,0.307984,93.9,-0.492927,0.621589,1,True,NaN,NaN,NaN,11.020142
350,tx2024hstr,4O,SA09,00,HHE,S,2024-04-19 21:08:42.271219,0.2,0.2,Fernando,...,0.343903,93.4,-0.971462,0.000000,1,True,NaN,NaN,NaN,11.802111
351,tx2024hstr,TX,PECS,00,HH1,S,2024-04-19 21:08:44.523686,0.2,0.2,Fernando,...,0.413340,92.7,-0.937691,0.000000,1,True,NaN,NaN,NaN,14.054578
352,tx2024hstr,TX,PB12,00,HHE,S,2024-04-19 21:08:47.163077,0.2,0.2,Fernando,...,0.503058,92.1,-1.286281,0.000000,1,True,55.753627,155.750460,335.875812,16.693969
353,tx2024hstr,TX,VHRN,00,HHZ,P,2024-04-19 21:08:51.149134,0.2,0.2,Fernando,...,1.113848,77.5,-0.948933,0.171817,1,True,NaN,NaN,NaN,20.680026

All information is extracted by their database. But, next columns are computed by utdquake

```
utdq_real	#real pick?
utdq_distance # Distance in km from the station to the source
utdq_azimuth	# Azimuth from the station to the source
utdq_bazimuth	# Back Azimuth from the station to the source
utdq_time # Travel time form the source to the station
```

utdq_real	utdq_distance	utdq_azimuth	utdq_bazimuth	utdq_time computed

# Others

In [ ]:
import pandas as pd

catalog = pd.read_csv(catalog_path)
stations = pd.read_csv(stations_path)

print(catalog.head())
print(stations.head())

        ev_id     ev_type agency                 origin_time  longitude  \
0  tx2024hrey  earthquake     TX  2024-04-19 00:33:29.083274   -103.884
1  tx2024hrgy  earthquake     TX  2024-04-19 01:33:51.844213   -104.194
2  tx2024hriz  earthquake     TX  2024-04-19 02:34:59.666935   -103.937
3  tx2024hrlf  earthquake     TX  2024-04-19 03:43:00.012014   -104.287
4  tx2024hrwl  earthquake     TX  2024-04-19 09:23:13.067845   -104.410

   latitude   depth loc_method_id        earth_model_id  magnitude  ...  \
0    31.488  6074.2     NonLinLoc  PB1D-20170918-topoLV        1.8  ...
1    31.612  4920.7     NonLinLoc  PB1D-20170918-topoLV        1.8  ...
2    31.605  5920.4     NonLinLoc  PB1D-20170918-topoLV        1.6  ...
3    31.717  6151.1     NonLinLoc  PB1D-20170918-topoLV        2.6  ...
4    31.677  5638.4     NonLinLoc  PB1D-20170918-topoLV        2.9  ...

  qc_magnitude_evaluation_status qc_associated_phase_count  \
0                      confirmed                        46
1                      confirmed                        65
2                      confirmed                        28
3                      confirmed                        75
4                      confirmed                        51

  qc_used_phase_count qc_associated_station_count qc_used_station_count  \
0                  23                         NaN                    20
1                  40                         NaN                    29
2                  17                         NaN                    12
3                  21                         NaN                    15
4                  30                         NaN                    23

   qc_arrivals_rms  qc_azimuthal_gap  qc_minimum_station_distance  \
0              0.1              60.0                          0.1
1              0.1              67.0                          0.1
2              0.1              84.0                          0.1
3              0.2              60.0                          0.0
4              0.1              69.0                          0.0

   qc_maximum_station_distance  qc_median_station_distance
0                          0.2                         0.2
1                          0.3                         0.2
2                          0.1                         0.1
3                          0.2                         0.2
4                          0.3                         0.3

[5 rows x 30 columns]
    sta_id network station   latitude   longitude  elevation  \
0  TX.PB01      TX    PB01  30.943670 -103.781120     1010.0
1  TX.PB02      TX    PB02  31.408951 -103.510162      792.0
2  TX.PB03      TX    PB03  31.083840 -103.513950      871.0
3  TX.PB04      TX    PB04  31.186970 -103.269400      812.0
4  TX.PB05      TX    PB05  30.919780 -103.324700      957.0

             starttime endtime                       site_name
0  2017-09-13 00:00:00     NaN            Balmorhea State Park
1  2017-01-27 00:00:00     NaN  Crockett Middle School (Pecos)
2  2021-07-28 03:30:00     NaN                        Verhalen
3  2019-02-12 00:00:00     NaN                        Verhalen
4  2016-11-05 00:00:00     NaN                 Permian Basin 5

picks and mags (all)

In [ ]:
from utdquake.core.database.database import load_from_sqlite

picks = load_from_sqlite(picks_path)
mags = load_from_sqlite(mags_path)

print(picks.head())
print(mags.head())

        ev_id network station location channel phase_hint  \
0  tx2024hrey      TX    PECS       00     HH2          P
1  tx2024hrey      TX    PECS       00     HH2          S
2  tx2024hrey      TX    PB40       00     HH1          P
3  tx2024hrey      TX    PB40       00     HH2          S
4  tx2024hrey      TX    PB43       00     HH1          P

                         time  time_lower_error  time_upper_error   author  \
0  2024-04-19 00:33:32.130765               0.2               0.2  Anestis
1  2024-04-19 00:33:34.698990               0.3               0.3  Anestis
2  2024-04-19 00:33:32.888062               0.2               0.2  Anestis
3  2024-04-19 00:33:36.081880               0.2               0.2  Anestis
4  2024-04-19 00:33:33.497192               0.1               0.1  Anestis

   ... polarity evaluation_mode evaluation_status time_correction     azimuth  \
0  ...     None          manual              None             0.0  173.168308
1  ...     None          manual              None             0.0  173.168308
2  ...     None          manual              None             0.0  344.669944
3  ...     None          manual              None             0.0  344.669944
4  ...     None          manual              None             0.0    5.007341

   distance  takeoff_angle  time_residual  time_weight  used
0  0.118924          106.1       0.020992     1.212390     1
1  0.118924          106.1       0.319143     0.000000     1
2  0.159579           93.6       0.007963     1.217838     1
3  0.159579           93.6       0.353910     0.000000     1
4  0.192496           81.2       0.005649     1.383258     1

[5 rows x 22 columns]
        ev_id network_code station_code location_code channel_code       mag  \
0  tx2024hrey           4O         WB04            00           HH  1.554133
1  tx2024hrey           TX         PB13            01           HH  2.036581
2  tx2024hrey           TX         PECS            00           HH  1.664017
3  tx2024hrey           4O         WB03            00           HH  1.888814
4  tx2024hrey           TX         PB33            00           HH  1.555783

  mag_type  residual  weight  used
0       ML -0.225091     0.0     1
1       ML  0.257357     0.0     1
2       ML -0.115207     1.0     1
3       ML  0.109590     1.0     1
4       ML -0.223441     0.0     1

by chunks

In [ ]:
from utdquake.core.database.database import load_chunks_from_sqlite

picks_chunks = load_chunks_from_sqlite(picks_path,chunksize=2)
mags_chunks = load_chunks_from_sqlite(mags_path,chunksize=2)

for picks in picks_chunks:
    print(picks)

for mags in mags_chunks:
    print(mags)

          ev_id network station location channel phase_hint  \
0    tx2024hrey      TX    PECS       00     HH2          P
1    tx2024hrey      TX    PECS       00     HH2          S
2    tx2024hrey      TX    PB40       00     HH1          P
3    tx2024hrey      TX    PB40       00     HH2          S
4    tx2024hrey      TX    PB43       00     HH1          P
..          ...     ...     ...      ...     ...        ...
106  tx2024hrgy      TX    PB12       00     HHZ          P
107  tx2024hrgy      GM   NMP11       01     HHZ          P
108  tx2024hrgy      US    MNTX       00     BHZ          P
109  tx2024hrgy      TX    PB46       00     HHZ          P
110  tx2024hrgy      TX    PB01       00     HHZ          P

                           time  time_lower_error  time_upper_error   author  \
0    2024-04-19 00:33:32.130765               0.2               0.2  Anestis
1    2024-04-19 00:33:34.698990               0.3               0.3  Anestis
2    2024-04-19 00:33:32.888062               0.2               0.2  Anestis
3    2024-04-19 00:33:36.081880               0.2               0.2  Anestis
4    2024-04-19 00:33:33.497192               0.1               0.1  Anestis
..                          ...               ...               ...      ...
106  2024-04-19 01:34:00.553498               0.2               0.2     Kate
107  2024-04-19 01:34:01.002831               0.2               0.2     Kate
108  2024-04-19 01:34:11.169726               0.2               0.2     Kate
109  2024-04-19 01:34:04.430101               0.2               0.2     Kate
110  2024-04-19 01:34:05.671268               0.2               0.2     Kate

     ... polarity evaluation_mode evaluation_status time_correction  \
0    ...     None          manual              None             0.0
1    ...     None          manual              None             0.0
2    ...     None          manual              None             0.0
3    ...     None          manual              None             0.0
4    ...     None          manual              None             0.0
..   ...      ...             ...               ...             ...
106  ...     None          manual              None             0.0
107  ...     None          manual              None             0.0
108  ...     None          manual              None             0.0
109  ...     None          manual              None             0.0
110  ...     None          manual              None             0.0

        azimuth  distance  takeoff_angle  time_residual  time_weight  used
0    173.168308  0.118924          106.1       0.020992     1.212390     1
1    173.168308  0.118924          106.1       0.319143     0.000000     1
2    344.669944  0.159579           93.6       0.007963     1.217838     1
3    344.669944  0.159579           93.6       0.353910     0.000000     1
4      5.007341  0.192496           81.2       0.005649     1.383258     1
..          ...       ...            ...            ...          ...   ...
106  153.366008  0.447110           69.0      -0.585264     0.213952     1
107   29.751796  0.454447           69.0      -0.244085     0.000000     1
108  275.555354  1.015789           65.7      -0.416572     0.489746     1
109   81.294246  0.620377           69.0       0.066131     0.904144     1
110  152.344962  0.756405           69.0      -1.279391     0.000000     1

[111 rows x 22 columns]
          ev_id network station location channel phase_hint  \
0    tx2024hriz      4O    WB03       00     HHN          P
1    tx2024hriz      4O    WB04       00     HHN          P
2    tx2024hriz      4O    WB04       00     HHE          S
3    tx2024hriz      TX    PB24       00     HHE          P
4    tx2024hriz      TX    PB24       00     HHE          S
..          ...     ...     ...      ...     ...        ...
98   tx2024hrlf      US    MNTX       00     BH1          P
99   tx2024hrlf      SC     DAG       00     HHN          P
100  tx2024hrlf      TX    PB04       00     HH1          P
101  tx2024hrlf      TX    VHRN       00     HH1          P
102  tx2024hrlf      TX    ALPN       00     HH1          P

                           time  time_lower_error  time_upper_error   author  \
0    2024-04-19 02:35:01.467856               0.2               0.2   Victor
1    2024-04-19 02:35:01.935576               0.2               0.2   Victor
2    2024-04-19 02:35:03.543267               0.2               0.2   Victor
3    2024-04-19 02:35:01.991986               0.2               0.2   Victor
4    2024-04-19 02:35:03.560190               0.2               0.2   Victor
..                          ...               ...               ...      ...
98   2024-04-19 03:43:17.739999               0.2               0.2  Anestis
99   2024-04-19 03:43:17.570490               0.2               0.2  Anestis
100  2024-04-19 03:43:20.016257               0.2               0.2  Anestis
101  2024-04-19 03:43:20.670075               0.2               0.2  Anestis
102  2024-04-19 03:43:26.118565               0.2               0.2  Anestis

     ... polarity evaluation_mode evaluation_status time_correction  \
0    ...        p          manual              None             0.0
1    ...        p          manual              None             0.0
2    ...     None          manual              None             0.0
3    ...        n          manual              None             0.0
4    ...     None          manual              None             0.0
..   ...      ...             ...               ...             ...
98   ...     None          manual              None             0.0
99   ...     None          manual              None             0.0
100  ...     None          manual              None             0.0
101  ...     None          manual              None             0.0
102  ...     None          manual              None             0.0

        azimuth  distance  takeoff_angle  time_residual  time_weight  used
0    280.980396  0.028059          152.6       0.204661     0.000000     1
1    189.120898  0.075963          121.0       0.020654     1.039167     1
2    189.120898  0.075963          121.0      -0.057739     1.029768     1
3    281.926204  0.070743          123.4       0.156621     0.000000     1
4    281.926204  0.070743          123.4       0.098409     0.977287     1
..          ...       ...            ...            ...          ...   ...
98   269.540151  0.933078           72.4      -0.407117     0.000000     1
99   339.077181  0.940084           72.4      -0.907572     0.000000     1
100  121.515367  1.017942           72.4       0.218444     0.000000     1
101  213.251611  1.106579           72.4      -0.876989     0.163510     1
102  157.731595  1.454281           72.4      -1.813588     0.000000     1

[103 rows x 22 columns]
         ev_id network station location channel phase_hint  \
0   tx2024hrwl      TX    PB35       00     HHZ          P
1   tx2024hrwl      TX    PB35       00     HH1          S
2   tx2024hrwl      TX    PB28       00     HHZ          P
3   tx2024hrwl      TX    PB28       00     HH1          S
4   tx2024hrwl      TX    PB37       00     HHZ          P
..         ...     ...     ...      ...     ...        ...
70  tx2024hrwo      SC    GDL2       00     HHE          P
71  tx2024hrwo      TX    VHRN       00     HH1          P
72  tx2024hrwo      TX    PECS       00     HH1          P
73  tx2024hrwo      TX    PB12       00     HHE          P
74  tx2024hrwo      TX    PB01       00     HH2          P

                          time  time_lower_error  time_upper_error  author  \
0   2024-04-19 09:23:14.804978               0.1               0.1    Kate
1   2024-04-19 09:23:15.796241               0.1               0.1    Kate
2   2024-04-19 09:23:15.436161               0.1               0.1    Kate
3   2024-04-19 09:23:16.806672               0.1               0.1    Kate
4   2024-04-19 09:23:15.928516               0.1               0.1    Kate
..                         ...               ...               ...     ...
70  2024-04-19 09:27:47.729743               0.2               0.2  Victor
71  2024-04-19 09:27:56.207114               0.2               0.2  Victor
72  2024-04-19 09:27:48.303402               0.2               0.2  Victor
73  2024-04-19 09:27:49.173089               0.2               0.2  Victor
74  2024-04-19 09:27:54.111840               0.2               0.2  Victor

    ... polarity evaluation_mode evaluation_status time_correction  \
0   ...        n          manual              None             0.0
1   ...     None          manual              None             0.0
2   ...        n          manual              None             0.0
3   ...     None          manual              None             0.0
4   ...        p          manual              None             0.0
..  ...      ...             ...               ...             ...
70  ...        p          manual              None             0.0
71  ...     None          manual              None             0.0
72  ...     None          manual              None             0.0
73  ...     None          manual              None             0.0
74  ...     None          manual              None             0.0

       azimuth  distance  takeoff_angle  time_residual  time_weight  used
0   222.862927  0.028174          152.4       0.123127     1.105508     1
1   222.862927  0.028174          152.4      -0.096124     1.287071     1
2   264.296141  0.078021          120.3       0.053843     1.312500     1
3   264.296141  0.078021          120.3      -0.311624     0.655206     1
4   292.826090  0.109312          111.8      -0.036623     1.375623     1
..         ...       ...            ...            ...          ...   ...
70    5.322135  0.531234           91.6      -0.291213     0.830135     1
71  209.343598  1.011200           77.5      -0.722743     0.233410     1
72  123.057229  0.558086           91.5      -0.153977     1.051206     1
73  139.830048  0.604018           91.4      -0.169870     1.025089     1
74  143.565086  0.909692           77.5      -0.878726     0.117787     1

[75 rows x 22 columns]
         ev_id network station location channel phase_hint  \
0   tx2024hstr      4O    SA02       00     HHZ          P
1   tx2024hstr      4O    SA02       00     HHN          S
2   tx2024hstr      4O    SA06       00     HHZ          P
3   tx2024hstr      4O    SA06       00     HHE          S
4   tx2024hstr      4O    SA04       00     HHZ          P
..         ...     ...     ...      ...     ...        ...
60  tx2024hstr      TX    PB56       00     CHN          S
61  tx2024hstr      TX    PB56       00     CHZ          P
62  tx2024hstr      TX    PB44       00     HHZ          P
63  tx2024hstr      TX    PB13       01     HHZ          P
64  tx2024hstr      4O    BP01     None     HHZ          P

                          time  time_lower_error  time_upper_error    author  \
0   2024-04-19 21:08:32.805341               0.1               0.1  Fernando
1   2024-04-19 21:08:34.125638               0.1               0.1  Fernando
2   2024-04-19 21:08:33.402822               0.1               0.1  Fernando
3   2024-04-19 21:08:35.147910               0.1               0.1  Fernando
4   2024-04-19 21:08:33.440303               0.1               0.1  Fernando
..                         ...               ...               ...       ...
60  2024-04-19 21:08:41.489250               0.2               0.2  Fernando
61  2024-04-19 21:08:37.178946               0.1               0.1  Fernando
62  2024-04-19 21:08:36.959495               0.1               0.1  Fernando
63  2024-04-19 21:08:37.559829               0.2               0.2  Fernando
64  2024-04-19 21:08:38.133197               0.2               0.2  Fernando

    ... polarity evaluation_mode evaluation_status time_correction  \
0   ...        n          manual              None             0.0
1   ...     None          manual              None             0.0
2   ...        p          manual              None             0.0
3   ...     None          manual              None             0.0
4   ...        p          manual              None             0.0
..  ...      ...             ...               ...             ...
60  ...     None          manual              None             0.0
61  ...        n          manual              None             0.0
62  ...        p          manual              None             0.0
63  ...     None          manual              None             0.0
64  ...     None          manual              None             0.0

       azimuth  distance  takeoff_angle  time_residual  time_weight  used
0   269.725673  0.057354          136.9       0.195849     0.962610     1
1   269.725673  0.057354          136.9      -0.089256     1.309443     1
2    25.982739  0.094160          117.2       0.254768     0.745071     1
3    25.982739  0.094160          117.2      -0.009516     1.362548     1
4   330.261219  0.096814          116.4       0.237028     0.811838     1
..         ...       ...            ...            ...          ...   ...
60   65.028798  0.307984           93.9      -0.492927     0.621589     1
61   65.028798  0.307984           93.9       0.131204     1.155642     1
62   35.713673  0.309119           93.9      -0.115778     1.265691     1
63  111.743136  0.322357           93.7       0.222010     0.825188     1
64   62.242156  0.359773           93.2       0.127734     1.011502     1

[65 rows x 22 columns]
         ev_id network_code station_code location_code channel_code       mag  \
0   tx2024hrey           4O         WB04            00           HH  1.554133
1   tx2024hrey           TX         PB13            01           HH  2.036581
2   tx2024hrey           TX         PECS            00           HH  1.664017
3   tx2024hrey           4O         WB03            00           HH  1.888814
4   tx2024hrey           TX         PB33            00           HH  1.555783
..         ...          ...          ...           ...          ...       ...
77  tx2024hrgy           4O         CV01          None          HHZ  1.750203
78  tx2024hrgy           TX         PB23            00          HHZ  1.906802
79  tx2024hrgy           TX         PB31            00          HHZ  1.931541
80  tx2024hrgy           TX         PB37            00          HHZ  1.401670
81  tx2024hrgy           TX         PB34            00          HHZ  2.201466

   mag_type  residual  weight  used
0        ML -0.225091     0.0     1
1        ML  0.257357     0.0     1
2        ML -0.115207     1.0     1
3        ML  0.109590     1.0     1
4        ML -0.223441     0.0     1
..      ...       ...     ...   ...
77      MLv       NaN     NaN     0
78      MLv       NaN     NaN     0
79      MLv       NaN     NaN     0
80      MLv       NaN     NaN     0
81      MLv       NaN     NaN     0

[82 rows x 10 columns]
         ev_id network_code station_code location_code channel_code       mag  \
0   tx2024hriz           4O         WB03            00           HH  1.310168
1   tx2024hriz           TX         PB24            00           HH  1.642379
2   tx2024hriz           4O         WB04            00           HH  2.001920
3   tx2024hriz           TX         PB13            01           HH  1.232949
4   tx2024hriz           TX         PB58            00           CH  1.907429
..         ...          ...          ...           ...          ...       ...
82  tx2024hrlf           TX         PB58            00          CHZ  2.890258
83  tx2024hrlf           4O         SA02            00          HHZ  2.886134
84  tx2024hrlf           4O         SA04            00          HHZ  2.927680
85  tx2024hrlf           TX         PB35            00          HHZ  2.330610
86  tx2024hrlf           TX         PB28            00          HHZ  2.474063

   mag_type  residual  weight  used
0        ML -0.287664     1.0     1
1        ML  0.044547     1.0     1
2        ML  0.404088     0.5     1
3        ML -0.364883     0.5     1
4        ML  0.309597     1.0     1
..      ...       ...     ...   ...
82      MLv       NaN     NaN     0
83      MLv       NaN     NaN     0
84      MLv       NaN     NaN     0
85      MLv       NaN     NaN     0
86      MLv       NaN     NaN     0

[87 rows x 10 columns]
         ev_id network_code station_code location_code channel_code       mag  \
0   tx2024hrwl           TX         PB35            00           HH  2.736482
1   tx2024hrwl           TX         PB38            00           HH  2.915530
2   tx2024hrwl           TX         PB28            00           HH  3.329729
3   tx2024hrwl           TX         PB37            00           HH  3.153461
4   tx2024hrwl           TX         PB29            00           HH  3.413326
5   tx2024hrwl           4O         SA02            00           HH  2.781695
6   tx2024hrwl           TX         PB09            00           BH  2.840873
7   tx2024hrwl           4O         SA07            00           HH  2.722254
8   tx2024hrwl           4O         SA06            00           HH  2.701891
9   tx2024hrwl           TX         PB26            00           HH  2.814371
10  tx2024hrwl           TX         PB23            00           HH  2.753099
11  tx2024hrwl           TX         PB20            00           HH  2.692858
12  tx2024hrwl           TX         PB25            00           HH  2.838358
13  tx2024hrwl           TX         PB34            00           HH  3.058479
14  tx2024hrwl           4O         CV01          None           HH  2.810569
15  tx2024hrwl           TX         PB31            00           HH  2.984726
16  tx2024hrwl           TX         PB33            00           HH  2.905778
17  tx2024hrwl           TX         PB24            00           HH  2.980484
18  tx2024hrwl           4O         CT02          None           HH  3.046682
19  tx2024hrwl           4O         WB04            00           HH  3.147959
20  tx2024hrwl           TX         PB28            00          HHZ  3.326245
21  tx2024hrwl           TX         PB23            00          HHZ  2.877418
22  tx2024hrwl           4O         SA06            00          HHZ  2.533980
23  tx2024hrwl           4O         CT02          None          HHZ  2.778787
24  tx2024hrwl           4O         SA02            00          HHZ  2.776707
25  tx2024hrwl           TX         PB34            00          HHZ  2.785271
26  tx2024hrwl           4O         CV01          None          HHZ  2.826220
27  tx2024hrwl           TX         PB31            00          HHZ  2.915918
28  tx2024hrwl           TX         PB35            00          HHZ  3.120730
29  tx2024hrwl           TX         PB25            00          HHZ  2.865467
30  tx2024hrwl           TX         PB37            00          HHZ  2.944277
31  tx2024hrwl           TX         PB20            00          HHZ  2.811873
32  tx2024hrwl           TX         PB26            00          HHZ  2.916439
33  tx2024hrwl           4O         WB04            00          HHZ  3.279252
34  tx2024hrwl           TX         PB24            00          HHZ  3.065668
35  tx2024hrwl           TX         PB09            00          BHZ  2.776824
36  tx2024hrwl           4O         SA07            00          HHZ  2.631815
37  tx2024hrwl           TX         PB29            00          HHZ  3.253208
38  tx2024hrwl           TX         PB33            00          HHZ  3.078559
39  tx2024hrwl           TX         PB38            00          HHZ  3.552379
40  tx2024hrwo           TX         PB35            00           HH  1.535693
41  tx2024hrwo           TX         PB38            00           HH  1.997131
42  tx2024hrwo           TX         PB28            00           HH  2.274841
43  tx2024hrwo           TX         PB37            00           HH  2.033354
44  tx2024hrwo           TX         PB29            00           HH  2.329156
45  tx2024hrwo           4O         SA02            00           HH  2.271076